name: 'end-to-end'

inputs:
  platform-is-running:
    required: false
    description: 'If false, spin up the platform and its resources'
    default: false
    type: boolean
  platform-ref:
    required: false
    description: 'The ref to check out for the platform'
    default: 'main'
    type: string
  otdfctl-ref:
    required: false
    description: 'The ref to check out for the otdfctl CLI'
    default: 'main'
    type: string

jobs:
  end-to-end:
    name: otdfctl CLI e2e tests
    runs-on: ubuntu-latest
    env:
      # Define 'bats' install location in ubuntu
      BATS_LIB_PATH: /usr/lib
      # Terminal width for testing printed output
      TEST_TERMINAL_WIDTH: 200
      # PLATFORM_IS_RUNNING: ${{ inputs.platform-is-running }}
      # PLATFORM_REF: ${{ inputs.platform-ref }}
      # OTDFCTL_REF: ${{ inputs.otdfctl-ref }}
    steps:
      - name: Report on the run context
        run: |
          if [ "${{ inputs.platform-is-running }}" == "true" ]; then
            echo "Platform is already running"
          else
            if [ "${{ inputs.platform-ref }}" == "" ]; then
              echo "Platform will be spun up from 'main'"
            else
              echo "Platform will be checked out at '${{ inputs.platform-ref }}' and spun up"
            fi
          fi

          if [ ${{ inputs.otdfctl-ref == github.event.pull_request.head.sha }} ]; then
            echo "otdfctl will be tested from the PR branch"
          else
            echo "otdfctl will be tested from 'main' or '${{ inputs.otdfctl-ref }}'"
          fi
      - name: Check out otdfctl CLI
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          ref: ${{ inputs.otdfctl-ref }}
        # Spin up the platform IFF it's not already running in the current workflow context
      - name: Check out platform
        if: ${{ ! inputs.platform-is-running }}
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          repository: opentdf/platform
          path: platform
          ref: ${{ inputs.platform-ref }}
      - name: Set up go (platform's go version)
        id: setup-go
        if: ${{ ! inputs.platform-is-running }}
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7
        with:
          go-version-file: 'platform/service/go.mod'
          check-latest: false
          cache-dependency-path: |
            platform/service/go.sum
            platform/protocol/go/go.sum
            platform/sdk/go.sum
      - name: Provide the platform with keys
        if: ${{ ! inputs.platform-is-running }}
        run: |
          .github/scripts/init-temp-keys.sh
          cp opentdf-dev.yaml opentdf.yaml
        working-directory: platform
      - name: Trust the generated certs
        if: ${{ ! inputs.platform-is-running }}
        run: |
          sudo chmod -R 777 ./keys
          sudo apt-get install -y ca-certificates
          sudo cp ./keys/localhost.crt /usr/local/share/ca-certificates
          sudo update-ca-certificates
        working-directory: platform
      - name: Spin up platform's containerized resources
        if: ${{ ! inputs.platform-is-running }}
        run: docker compose up -d --wait --wait-timeout 240
        working-directory: platform
      - name: Provision realms/clients/users into idP
        if: ${{ ! inputs.platform-is-running }}
        run: go run ./service provision keycloak
        working-directory: platform
      - name: Provision test fixture policy
        if: ${{ ! inputs.platform-is-running }}
        run: go run ./service provision fixtures
        working-directory: platform
      - name: Start platform server in background
        if: ${{ ! inputs.platform-is-running }}
        uses: JarvusInnovations/background-action@2428e7b970a846423095c79d43f759abf979a635
        with:
          run: >
            go build -o opentdf -v service/main.go
            && .github/scripts/watch.sh opentdf.yaml ./opentdf start
          wait-on: |
            tcp:localhost:8080
          log-output-if: true
          wait-for: 90s
          working-directory: platform

      # Build the CLI and run tests
      - name: Set up go (CLI version, if needed)
        if: steps.setup-go.outcome != 'success'
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7
        with:
          go-version-file: go.mod
      - name: Build the CLI
        run: go build .
      - name: Build the CLI in test mode
        run: make build-test
      - name: Set up the CLI config
        run: cp otdfctl-example.yaml otdfctl.yaml
      - name: Setup Bats and bats libs
        uses: bats-core/bats-action@2.0.0
      - run: e2e/encrypt-decrypt.bats
      - run: e2e/kas-grants.bats
      - run: e2e/profile.bats
      - run: e2e/kas-registry.bats
      - run: e2e/namespaces.bats
