name: '🧹 Lint PR Title'
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-22.04
    steps:
      - uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017
        with:
          types: |
            fix
            feat
            chore
            docs
          scopes: |
            main
            core
            tui
            demo
            ci
            dependabot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
